export const GET_LOTR_STARTED = 'GET_LOTR_STARTED';
export const GET_LOTR_SUCCESS = 'GET_LOTR_SUCCESS';
export const GET_LOTR_FAILED = 'GET_LOTR_FAILED';

export const GET_CATS_STARTED = 'GET_CATS_STARTED';
export const GET_CATS_SUCCESS = 'GET_CATS_SUCCESS';
export const GET_CATS_FAILED = 'GET_CATS_FAILED';